### ISSUE TITLE
Add Babel Plugins

### ISSUE THREAD

**Issue by agungsb** [ayroblu/ssr-create-react-app-v2#6]
Is there anyway to add babel plugins?

I added `babel-resolver` and `babel-plugin-transform-remove-console` modules to the project. Then I made some edit in `app.js`:

```var basePath = path.resolve(__dirname, '..', 'src')
require('babel-register')({
  ignore: /\/(build|node_modules)\//,
  presets: ['env', 'react-app'],
  plugins: [
    "transform-remove-console"
  ],
  resolveModuleSource: require('babel-resolver')(basePath)
})
```

The `babel-resolver` works fine, but the `transform-remove-console` seems not processed at all.

Any thoughts, @ayroblu ? Thanks.

**Comment by ayroblu** [comment]
Umm, not sure if this is server side or client side. app js is client side right? Perhaps adjusting a babelrc might work? But yeah alittle confused where this is
